# Generated by Django 4.0.4 on 2022-04-25 15:27

import HumanResource.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='考勤状态')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='部门名称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', HumanResource.models.GenderField(choices=[(0, '男'), (1, '女'), (2, '其他')], default=2, verbose_name='性别')),
                ('attendance_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HumanResource.attendancestatus', verbose_name='考勤状态')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HumanResource.department', verbose_name='部门')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
